<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Moq" Version="4.21.0" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MovieManager.Logic\MovieManager.Logic.csproj" />
    <ProjectReference Include="..\MovieManager.Models\MovieManager.Models.csproj" />
    <ProjectReference Include="..\MovieManager.Repository\MovieManager.Repository.csproj" />
  </ItemGroup>

</Project>
